// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPAGinXOIlwEIhgRd1cqWXL73HEOVvZBA',
    appId: '1:617933645652:web:4e8816fb3e36fe674c4ac1',
    messagingSenderId: '617933645652',
    projectId: 'instgram-e7b45',
    authDomain: 'instgram-e7b45.firebaseapp.com',
    storageBucket: 'instgram-e7b45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiaFfuQVRhCANsQHNLZrrxTEXqColeqzY',
    appId: '1:617933645652:android:63a7a1c2bc866b8d4c4ac1',
    messagingSenderId: '617933645652',
    projectId: 'instgram-e7b45',
    storageBucket: 'instgram-e7b45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnFvNGVoYd9bkBsjmKAP_WZogFnTN4kqU',
    appId: '1:617933645652:ios:c3b90b43e8b91f744c4ac1',
    messagingSenderId: '617933645652',
    projectId: 'instgram-e7b45',
    storageBucket: 'instgram-e7b45.appspot.com',
    iosClientId: '617933645652-paqu39ab2f651k0t8speelu19aqit45l.apps.googleusercontent.com',
    iosBundleId: 'com.example.instgram',
  );
}
